# Generated by Django 3.2.7 on 2021-09-09 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0002_register'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='user_type',
            field=models.CharField(choices=[('student', 'student'), ('teacher', 'teacher')], default='student', max_length=30),
        ),
    ]
