# Generated by Django 3.1.4 on 2021-11-15 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0006_auto_20211023_1146'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
